name: Build flipPlots

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build flipPlots
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@master
    with:
      installable-path: pkgs.x86_64-linux.rPackages.flipPlots
      build-args: --override-input flipPlots .
      installable-name: flipPlots
    secrets: inherit
